=== markof94/ist2021/backend/proizvodi.dtd
<!ELEMENT Prodavnica (Proizvod+)>
<!ELEMENT Proizvod (Kategorija,Cena,Tekst,Tag,Akcija?)>
<!ELEMENT Kategorija EMPTY>
<!ATTLIST Kategorija vrsta (laptopovi|tastature|stolice) #REQUIRED>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta NMTOKEN "RSD">
<!ELEMENT Tekst (#PCDATA)>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT Akcija EMPTY>
<!ATTLIST Akcija cena NMTOKEN #REQUIRED>
<!ATTLIST Akcija datumIsteka NMTOKEN #REQUIRED>

=== markof94/ist2021/backend/proizvodi.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE Prodavnica SYSTEM "proizvodi.dtd">
<?xml-model href="proizvodi.xsd"?>
<Prodavnica>
  <Proizvod>
    <Kategorija vrsta="laptopovi"></Kategorija>
    <Cena valuta="RSD">149999</Cena>
    <Tekst>Laptop ACER Rage 9001 Pro</Tekst>
    <Tag>laptop desktop acer pro gamer</Tag>
    <Akcija cena="124999" datumIsteka="2021-05-01"></Akcija>
  </Proizvod>

  <Proizvod>
    <Kategorija vrsta="laptopovi"></Kategorija>
    <Cena valuta="RSD">134999</Cena>
    <Tekst>Laptop HP Pavillion Doomboy X</Tekst>
    <Tag>laptop desktop hp pavillion gamer</Tag>
  </Proizvod>

  <Proizvod>
    <Kategorija vrsta="laptopovi"></Kategorija>
    <Cena valuta="RSD">49999</Cena>
    <Tekst>Laptop HP Scrub Office</Tekst>
    <Tag>laptop desktop hp office notebook</Tag>
  </Proizvod>

  <Proizvod>
    <Kategorija vrsta="stolice"></Kategorija>
    <Cena valuta="RSD">19999</Cena>
    <Tekst>Kancelarijska Fotelja</Tekst>
    <Tag>fotelja stolica kancelarija udobno</Tag>
    <Akcija cena="16999" datumIsteka="2021-06-05"></Akcija>
  </Proizvod>

  <Proizvod>
    <Kategorija vrsta="tastature"></Kategorija>
    <Cena valuta="RSD">4999</Cena>
    <Tekst>Gejmerska Tastatura - Mehanicka</Tekst>
    <Tag>tastatura gaming mehanicka rgb</Tag>
  </Proizvod>

  <Proizvod>
    <Kategorija vrsta="tastature"></Kategorija>
    <Cena valuta="RSD">5599</Cena>
    <Tekst>Gejmerska Tastatura - RGB</Tekst>
    <Tag>tastatura gaming rgb</Tag>
  </Proizvod>
</Prodavnica>
